name: give-tips-on-new-pr
on:
  pull_request:
    types: [ opened ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [self-hosted]
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Release ${{ github.sha }} to <https://pr-${{ github.event.number }}.example.com>
